/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.graforutamuni;

import GrafosPkg.Grafo;
import MuniGrafos.GrafoDire;

public class Ruta extends javax.swing.JFrame {

    /**
     * Creates new form Ruta
     */
    
    Grafo grafo = new Grafo("abcdefghijklmnñop");
    
    public Ruta() {
        initComponents();
        grafo.agregarRuta('a', 'ñ', 16);
        grafo.agregarRuta('b', 'c', 30);
        grafo.agregarRuta('b', 'ñ', 17);
        grafo.agregarRuta('b', 'g', 20);
        grafo.agregarRuta('b', 'o', 20);
        grafo.agregarRuta('c', 'b', 30);
        grafo.agregarRuta('c', 'o', 15);
        grafo.agregarRuta('c', 'i', 12);
        grafo.agregarRuta('d', 'm', 27);
        grafo.agregarRuta('d', 'h', 17);
        grafo.agregarRuta('e', 'h', 20);
        grafo.agregarRuta('e', 'k', 7);
        grafo.agregarRuta('f', 'o', 7);
        grafo.agregarRuta('f', 'p', 6);
        grafo.agregarRuta('f', 'i', 17);
        grafo.agregarRuta('g', 'j', 15);
        grafo.agregarRuta('g', 'b', 20);
        grafo.agregarRuta('g', 'ñ', 19);
        grafo.agregarRuta('h', 'n', 35);
        grafo.agregarRuta('h', 'd', 17);
        grafo.agregarRuta('h', 'e', 20);
        grafo.agregarRuta('i', 'c', 12);
        grafo.agregarRuta('i', 'o', 16);
        grafo.agregarRuta('i', 'p', 18);
        grafo.agregarRuta('i', 'f', 17);
        grafo.agregarRuta('j', 'm', 20);
        grafo.agregarRuta('j', 'g', 15);
        grafo.agregarRuta('j', 'o', 23);
        grafo.agregarRuta('k', 'e', 7);
        grafo.agregarRuta('k', 'l', 41);
        grafo.agregarRuta('l', 'k', 41);
        grafo.agregarRuta('m', 'n', 20);
        grafo.agregarRuta('m', 'j', 20);
        grafo.agregarRuta('m', 'd', 27);
        grafo.agregarRuta('n', 'h', 35);
        grafo.agregarRuta('n', 'm', 20);
        grafo.agregarRuta('ñ', 'g', 19);
        grafo.agregarRuta('ñ', 'b', 17);
        grafo.agregarRuta('ñ', 'a', 16);
        grafo.agregarRuta('o', 'j', 23);
        grafo.agregarRuta('o', 'b', 20);
        grafo.agregarRuta('o', 'c', 15);
        grafo.agregarRuta('o', 'i', 16);
        grafo.agregarRuta('o', 'p', 10);
        grafo.agregarRuta('o', 'f', 7);
        grafo.agregarRuta('p', 'o', 10);
        grafo.agregarRuta('p', 'f', 6);
        grafo.agregarRuta('p', 'i', 18);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BUSQUEDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 204, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AguaBlanca", "AsuncionMita", "Atescatempa", "Comapa", "Conguaco", "ElAdelanto", "ElProgreso", "Jalpatagua", "Jerez", "Jutiapa", "Moyuta", "Pasaco", "Quesada", "SanJoseAcatempa", "SantaCatarinaMita", "Yupiltepeque", "Zapotitlan" }));

        jComboBox2.setBackground(new java.awt.Color(255, 204, 0));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AguaBlanca", "AsuncionMita", "Atescatempa", "Comapa", "Conguaco", "ElAdelanto", "ElProgreso", "Jalpatagua", "Jerez", "Jutiapa", "Moyuta", "Pasaco", "Quesada", "SanJoseAcatempa", "SantaCatarinaMita", "Yupiltepeque", "Zapotitlan" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Distancia entre Municipios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        GrafoDire d = new GrafoDire();
        String InM;
        String FiM;             
        InM = jComboBox1.getSelectedItem() + "";
        FiM = jComboBox2.getSelectedItem() + "";      
        char inm = d.MuniJ(InM);
        char fim = d.MuniJ(FiM);
        String municipios = grafo.encontrarRutaMinimaDijkstra(inm, fim);
        jTextArea1.setText(municipios);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
